apiVersion: v1
kind: Service     # Indicates this as a service
metadata:
  name: reddit-app-service  # Service name
spec:
  type: LoadBalancer
  selector:
    app: reddit-app     # Selector for Pods
  ports:                 # Port Mapping
    - protocol: TCP
      port: 3000
      targetPort: 3000
      